mechanism: soda.mechanism.single_item.SingleItemAuction
bidder: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1']
o_space:
  '1': [0.0 ,1.0]
a_space:
  '1': [0.0 ,1.0]
param_prior:
  distribution: 'gaussian_trunc'
  mu: 0.5
  sigma: 0.3
param_util:
  payment_rule: 'second_price'
  tie_breaking: 'lose'
  utility_type: 'QL'
  reserve_price: 0.05
n: 64
m: 64