mechanism: soda.mechanism.single_item.SingleItemAuction
bidder: ['1', '1']
o_space:
  '1': [0.0 ,1.0]
a_space:
  '1': [0.0 ,0.8]
param_prior:
  distribution: 'uniform'
param_util:
  payment_rule: 'first_price'
  tie_breaking: 'lose'
  utility_type: 'CRRA'
  utility_type_parameter: 0.8
n: 64
m: 64