mechanism: soda.mechanism.crowdsourcing.Crowdsourcing 
bidder: ['1', '1', '1']
o_space:
    '1': [0.0, 1.0]
a_space:
    '1': [0.0, 1.0]
param_prior:
    distribution: 'uniform'
param_util:
    prices: [1.0, 0.0]
    payment_rule: 'first_price'
    tie_breaking: 'lose'
    type: value 
n: 64
m: 64