mechanism: soda.mechanism.contest_game.ContestGame
bidder: ['weak', 'strong']
o_space:
  'weak': [0.0, 1.0]
  'strong': [2.0, 3.0]
a_space:
  'weak': [0.0, 0.5]
  'strong': [0.0, 0.5]
param_prior: 
  distribution: 'uniform'
param_util:
  type: 'value'
  csf: 'ratio_form'
  csf_parameter: 0.5
n: 128
m: 128