mechanism: soda.mechanism.single_item.SingleItemAuction
bidder: ['1', '1', '1']
o_space:
  '1': [0.0 ,1.0]
a_space:
  '1': [0.0 ,1.0]
param_prior:
  distribution: 'uniform'
  midpoint: False
param_util:
  payment_rule: 'first_price'
  tie_breaking: 'lose'
  utility_typle: 'ROI'
  reserve_price: 0.05
n: 21
m: 21
bne_known: False