name: 'tullock_contest_concave1'
bidder: ['1', '1']
o_space: {'1': [0.1 ,1.1]}
a_space: {'1': [0.0, 0.3]}
param_prior: {'distribution': 'uniform'}
csf: 'ratio_form_valuation'
param_csf: 0.5
n: 128
m: 128