name: 'all_pay_loss_avers_1'
bidder: ['1', '1']
o_space: {'1': [0.0 ,1.0]}
a_space: {'1': [0.0, 0.7]}
param_prior: {'distribution': 'uniform'}
util_setting: 'loss_aversion_simple'
param_util: {'lambda': 1}
n: 128
m: 128