name: 'common_value'
mechanism: 'single_item'
bidder: ['1', '1', '1']
o_space: {'1': [0.0 ,2.0]}
a_space: {'1': [0.0 ,1.5],}
param_prior: {'distribution':'common_value'}
param_util: {
  'payment_rule': 'second_price', 
  'tie_breaking': 'lose'}
n: 64
m: 64
bne_known: True