mechanism: soda.mechanism.single_item.SingleItemAuction
bidder: ['1', '1', '1']
o_space:
  '1': [0.0 ,2.0]
a_space:
  '1': [0.0 ,1.5]
param_prior:
  distribution: 'common_value'
param_util:
  tie_breaking: 'lose'
  payment_rule: 'second_price'
  utility_type: 'QL'
n: 64
m: 64