learner: soda.learner.dual_averaging.SODA
max_iter: 1000
tol: 1e-4
stop_criterion: 'util_loss'
parameter:
  regularizer: 'euclidean'
  steprule_bool: True
  eta: 0.50
  beta: 0.05
init_method: 'random'