learner: soda.learner.mirror_descent.SOMA
max_iter: 1000
tol: 1e-4
stop_criterion: 'util_loss'
parameter:
  mirror_map: 'euclidean'
  steprule_bool: True
  eta: 0.05
  beta: 0.50
init_method: 'random'