name: 'crowdsourcing_val_no_ties_3_price3'
bidder: ['1', '1', '1']
o_space: {'1': [0.0 ,1.0]}
a_space: {'1': [0.0, 1.0]}
param_prior: {'distribution':'uniform'}
param_util: {'tiebreaking':'lose', 'type':'valuation'}
price: [0.6, 0.4]
n: 128
m: 128