mechanism: soda.mechanism.single_item.SingleItemAuction
bidder: ['1', '1']
o_space:
  '1': [0.0 ,1.0]
a_space:
  '1': [0.0 ,1.0]
param_prior:
  distribution: 'uniform'
param_util:
  payment_rule: 'second_price'
  tie_breaking: 'lose'
  utility_type: 'QL'
  reserve_price: 0.05
  budget: 1.01
  budget_parameter: 0.5
n: 64
m: 64
bne_known: False