mechanism: soda.mechanism.single_item.SingleItemAuction
bidder: ['1', '1']
o_space:
  '1': [0.0 ,1.0]
a_space:
  '1': [0.0 ,0.8]
param_prior:
  distribution: 'uniform'
param_util:
  payment_rule: 'second_price'
  tie_breaking: 'lose'
  utility_type: 'ROS'
  reserve_price: 0.05
  budget: 0.81
  budget_parameter: 1.0
n: 64
m: 64
bne_known: False