mechanism: soda.mechanism.single_item.SingleItemAuctionAsymmetric
bidder: ['roi', 'ros']
o_space:
  'roi': [0.0 ,1.0]
  'ros': [0.0 ,1.0]
a_space:
  'roi': [0.0 ,1.0]
  'ros': [0.0 ,1.0]
param_prior:
  distribution: 'uniform'
param_util:
  payment_rule: 'first_price'
  tie_breaking: 'lose'
  reserve_price: 0.05
  utility_type: ['ROI', 'ROS']
  'budget': [None, 1.01]
  'budget_parameter': [0.0, 1.0]
n: 64
m: 64