mechanism: soda.mechanism.single_item.SingleItemAuctionAsymmetric
bidder: ['ros', 'ros']
o_space:
  'ros': [0.0 ,1.0]
a_space:
  'ros': [0.0 ,1.0]
param_prior:
  distribution: 'uniform'
param_util:
  payment_rule: 'second_price'
  tie_breaking: 'lose'
  reserve_price: 0.05
  utility_type: ['ROS', 'ROS']
  'budget': [1.01, 1.01]
  'budget_parameter': [1.0, 1.0]
n: 64
m: 64