name: 'difference_form_val_0.5'
bidder: ['1', '1']
o_space: {'1': [0.1 ,1.1]}
a_space: {'1': [0.0, 2.2]}
param_prior: {'distribution':'uniform'}
csf: 'difference_form_valuation'
param_csf: 0.5
n: 128
m: 128