name: 'tullock_contest_3_val_0.5'
bidder: ['1', '1', '1']
o_space: {'1': [0.0 ,1.0]}
a_space: {'1': [0.0, 0.3]}
param_prior: {'distribution': 'uniform'}
param_util : {
  'csf': 'ratio_form_valuation',
  'param_csf': 0.5,
}
n: 64
m: 64
bne_known: False