name: 'tullock_lottery_weak_vs_strong2'
bidder: ['weak', 'strong']
o_space: {'weak': [0.0 ,1.0], 'strong': [2.0, 3.0]}
a_space: {'weak': [0.0, 0.4], 'strong': [0.0, 0.5]}
param_prior: {'distribution':'uniform'}
csf: 'ratio_form_valuation'
param_csf: 1
n: 128
m: 128
bne_known: False