name: 'tullock_contest_3_val_2'
bidder: ['1', '1', '1']
o_space: {'1': [0.0 ,1.0]}
a_space: {'1': [0.0, 0.5]}
param_prior: {'distribution':'uniform'}
csf: 'ratio_form_valuation'
param_csf: 2
n: 128
m: 128
bne_known: False